### ISSUE TITLE
Код ревью №1

### ISSUE THREAD

**Issue by bigman212** [Limas94/Zadachi-React#1]
Если в конструкторе инициализируется только state, лучше перенести его как поле
```js
class Foo extends Component {
  state = {
    foo: 'hello'
  }
...
}
```

Почему биндить в onClick вместо конструктора? 
https://github.com/Limas94/Zadachi-React/blob/aeb3fb57add8ae933c6b0f8813ca171fea78f73a/%D0%97%D0%B0%D0%B4%D0%B0%D1%87%D0%BD%D0%B8%D0%BA%20%D0%A2%D1%80%D0%B5%D0%BF%D0%B0%D1%87%D1%91%D0%B2%D0%B0/%D0%A3%D1%80%D0%BE%D0%BA%202.%20%D0%A1%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D0%B5%20state%20%D0%B8%20%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D1%8F/task_4/src/App.js#L26

**Comment by Limas94** [comment]
В данном случае согласен, что лучше биндить в конструкторе. Однако на сайте (по которому записываю решения) показывается бинд именно таким образом.

p.s. Только увидел соммент -_-
